language: node_js

branches:
  only:
  - master

node_js:
  - v11.0.0

before_deploy:
  - npm install

jobs:
  include:
    - stage: unit tests
      script: npm run test
    - stage: npm release
        deploy:
          provider: npm
          skip_cleanup: true
          email: 'a13868300128a@gmail.com'
          api_key: $NPM_API_KEY
          on: 
            all_branches: true
