language: node_js

branches:
  only:
  - master

node_js:
  - v11.0.0

before_deploy:
  - npm install

jobs:
  include:
    - stage: unit tests
      script: npm run test
    - stage: npm release
      script: echo "Deploying to npm ..."
      deploy:
        provider: npm
        api_key: $NPM_API_KEY
        on: 
          all_branches: true


after_success: echo 'success!'
